/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.71
 * Generated at: 2023-06-08 11:25:24 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.quanly;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class nhaphang_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(5);
    _jspx_dependants.put("jar:file:/D:/Workspace2/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Highlands/WEB-INF/lib/jstl-impl.jar!/META-INF/c.tld", Long.valueOf(1343794618000L));
    _jspx_dependants.put("/WEB-INF/common/quanly/header.jsp", Long.valueOf(1684209914560L));
    _jspx_dependants.put("jar:file:/D:/Workspace2/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Highlands/WEB-INF/lib/spring-webmvc-4.0.1.RELEASE.jar!/META-INF/spring-form.tld", Long.valueOf(1390885082000L));
    _jspx_dependants.put("/WEB-INF/lib/spring-webmvc-4.0.1.RELEASE.jar", Long.valueOf(1679084744000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-impl.jar", Long.valueOf(1679084736000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\" />\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\" />\r\n");
      out.write("<meta name=\"viewport\"\r\n");
      out.write("	content=\"width=device-width, initial-scale=1, shrink-to-fit=no\" />\r\n");
      out.write("<meta name=\"description\" content=\"\" />\r\n");
      out.write("<meta name=\"author\" content=\"\" />\r\n");
      out.write("<title>Nhập hàng</title>\r\n");
      out.write("<style>\r\n");
      out.write("label {\r\n");
      out.write("	display: block;\r\n");
      out.write("	font: 1rem 'Fira Sans', sans-serif;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("input, label {\r\n");
      out.write("	margin: 0.4rem 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("td:nth-child(n+3):nth-child(-n+6) {\r\n");
      out.write("	text-align: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("td:nth-child(4) {\r\n");
      out.write("	background-color: #C8E2B1;\r\n");
      out.write("	text-align: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("td:nth-child(5) {\r\n");
      out.write("	background-color: #C8E2B1;\r\n");
      out.write("	text-align: center;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<link\r\n");
      out.write("	href=\"https://cdn.jsdelivr.net/npm/simple-datatables@latest/dist/style.css\"\r\n");
      out.write("	rel=\"stylesheet\" />\r\n");
      out.write("<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${root}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/quanly/css/styles.css\" rel=\"stylesheet\" />\r\n");
      out.write("<script src=\"https://use.fontawesome.com/releases/v6.1.0/js/all.js\"\r\n");
      out.write("	crossorigin=\"anonymous\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body class=\"sb-nav-fixed\">\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("<nav class=\"sb-topnav navbar navbar-expand navbar-dark bg-dark\">\r\n");
      out.write("	<!-- Navbar Brand-->\r\n");
      out.write("	<a class=\"navbar-brand ps-3\"\r\n");
      out.write("		href=\"http://localhost:8080/Highlands/home/trangchuquanly.htm\">Quản\r\n");
      out.write("		Lý</a>\r\n");
      out.write("	<!-- Sidebar Toggle-->\r\n");
      out.write("	<button class=\"btn btn-link btn-sm order-1 order-lg-0 me-4 me-lg-0\"\r\n");
      out.write("		id=\"sidebarToggle\" href=\"#!\">\r\n");
      out.write("		<i class=\"fas fa-bars\"></i>\r\n");
      out.write("	</button>\r\n");
      out.write("	<ul class=\"navbar-nav ms-auto ms-md-0 me-3 me-lg-4\">\r\n");
      out.write("		<li class=\"nav-item dropdown\"><a class=\"nav-link dropdown-toggle\"\r\n");
      out.write("			id=\"navbarDropdown\" href=\"#\" role=\"button\" data-bs-toggle=\"dropdown\"\r\n");
      out.write("			aria-expanded=\"false\"><i class=\"fas fa-user fa-fw\"></i></a>\r\n");
      out.write("			<ul class=\"dropdown-menu dropdown-menu-end\"\r\n");
      out.write("				aria-labelledby=\"navbarDropdown\">\r\n");
      out.write("				<li><a class=\"dropdown-item\" href=\"http://localhost:8080/Highlands/home/profile.htm\">Hồ sơ của bạn</a></li>\r\n");
      out.write("				<li><a class=\"dropdown-item\" href=\"http://localhost:8080/Highlands/home/changepassword.htm\">Đổi Mật Khẩu</a></li>\r\n");
      out.write("				<li><hr class=\"dropdown-divider\" /></li>\r\n");
      out.write("				<li><a class=\"dropdown-item\" href=\"http://localhost:8080/Highlands/login/logout.htm\">Đăng Xuất</a></li>\r\n");
      out.write("			</ul></li>\r\n");
      out.write("	</ul>\r\n");
      out.write("</nav>\r\n");
      out.write("<div id=\"layoutSidenav\">\r\n");
      out.write("	<div id=\"layoutSidenav_nav\">\r\n");
      out.write("		<nav class=\"sb-sidenav accordion sb-sidenav-dark\"\r\n");
      out.write("			id=\"sidenavAccordion\">\r\n");
      out.write("			<div class=\"sb-sidenav-menu\">\r\n");
      out.write("				<div class=\"nav\">\r\n");
      out.write("					<div class=\"sb-sidenav-menu-heading\">Bán hàng</div>\r\n");
      out.write("					<a class=\"nav-link\" href=\"http://localhost:8080/Highlands/product/viewSP.htm\">Bán hàng</a> \r\n");
      out.write("					\r\n");
      out.write("					<div class=\"sb-sidenav-menu-heading\">Quản lý</div>\r\n");
      out.write("					<a class=\"nav-link collapsed\" href=\"#\" data-bs-toggle=\"collapse\"\r\n");
      out.write("						data-bs-target=\"#collapseLayouts\" aria-expanded=\"false\"\r\n");
      out.write("						aria-controls=\"collapseLayouts\">\r\n");
      out.write("						<div class=\"sb-nav-link-icon\">\r\n");
      out.write("							<i class=\"fas fa-columns\"></i>\r\n");
      out.write("						</div> Quản Lý\r\n");
      out.write("						<div class=\"sb-sidenav-collapse-arrow\">\r\n");
      out.write("							<i class=\"fas fa-angle-down\"></i>\r\n");
      out.write("						</div>\r\n");
      out.write("					</a>\r\n");
      out.write("					<div class=\"collapse\" id=\"collapseLayouts\"\r\n");
      out.write("						aria-labelledby=\"headingOne\" data-bs-parent=\"#sidenavAccordion\">\r\n");
      out.write("						<nav class=\"sb-sidenav-menu-nested nav\">\r\n");
      out.write("							<a class=\"nav-link\" href=\"http://localhost:8080/Highlands/employee/list.htm\">Nhân viên</a> \r\n");
      out.write("							<a class=\"nav-link\" href=\"http://localhost:8080/Highlands/product/list.htm\">Sản phẩm</a>\r\n");
      out.write("							<a class=\"nav-link\" href=\"http://localhost:8080/Highlands/product/type/list.htm\">Loại sản phẩm</a>\r\n");
      out.write("							<a class=\"nav-link\" href=\"http://localhost:8080/Highlands/product/size/list.htm\">Size sản phẩm</a>\r\n");
      out.write("							<a class=\"nav-link\" href=\"http://localhost:8080/Highlands/product/recipe/list.htm\">Công thức</a>\r\n");
      out.write("							<a class=\"nav-link\" href=\"http://localhost:8080/Highlands/material/list.htm\">Nguyên vật liệu</a> \r\n");
      out.write("							<a class=\"nav-link\" href=\"http://localhost:8080/Highlands/import/defineId.htm\">Nhập nguyên liệu</a> \r\n");
      out.write("							<a class=\"nav-link\" href=\"http://localhost:8080/Highlands/product/detail/list.htm\">Chi tiết sản phẩm</a>\r\n");
      out.write("							<a class=\"nav-link\" href=\"http://localhost:8080/Highlands/product/detailMaterial/list.htm\">Chi tiết nguyên liệu</a>\r\n");
      out.write("							<a class=\"nav-link\" href=\"http://localhost:8080/Highlands/promotion/list.htm\">Khuyến mãi</a>\r\n");
      out.write("							<a class=\"nav-link\" href=\"http://localhost:8080/Highlands/bill.htm\">Hóa đơn</a> \r\n");
      out.write("							\r\n");
      out.write("						\r\n");
      out.write("						</nav>\r\n");
      out.write("					</div>\r\n");
      out.write("					<a class=\"nav-link collapsed\" href=\"#\" data-bs-toggle=\"collapse\"\r\n");
      out.write("						data-bs-target=\"#collapsePages\" aria-expanded=\"false\"\r\n");
      out.write("						aria-controls=\"collapsePages\">\r\n");
      out.write("						<div class=\"sb-nav-link-icon\">\r\n");
      out.write("							<i class=\"fas fa-book-open\"></i>\r\n");
      out.write("						</div> Xem\r\n");
      out.write("						<div class=\"sb-sidenav-collapse-arrow\">\r\n");
      out.write("							<i class=\"fas fa-angle-down\"></i>\r\n");
      out.write("						</div>\r\n");
      out.write("					</a>\r\n");
      out.write("					<div class=\"collapse\" id=\"collapsePages\"\r\n");
      out.write("						aria-labelledby=\"headingTwo\" data-bs-parent=\"#sidenavAccordion\">\r\n");
      out.write("						<nav class=\"sb-sidenav-menu-nested nav accordion\"\r\n");
      out.write("							id=\"sidenavAccordionPages\">\r\n");
      out.write("							<a class=\"nav-link\" href=\"http://localhost:8080/Highlands/statistics.htm\">Thống kê</a>\r\n");
      out.write("							<a class=\"nav-link\" href=\"http://localhost:8080/Highlands/history/list.htm\">Lịch sử thay đổi giá</a>\r\n");
      out.write("							\r\n");
      out.write("						</nav>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"sb-sidenav-footer\">\r\n");
      out.write("				<div class=\"small\">Logged in as:</div>\r\n");
      out.write("				Quản lý\r\n");
      out.write("			</div>\r\n");
      out.write("		</nav>\r\n");
      out.write("	</div>");
      out.write("\r\n");
      out.write("	<div id=\"layoutSidenav_content\">\r\n");
      out.write("		<main>\r\n");
      out.write("			<div class=\"container-fluid px-4\">\r\n");
      out.write("				<div class=\"card-header\">\r\n");
      out.write("					<label class=\"font-weight-bold\"\r\n");
      out.write("						style=\"font-size: 20px; color: red; font-weight: bold;\">THÔNG\r\n");
      out.write("						TIN NHẬP HÀNG</label>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"card-header\">\r\n");
      out.write("					<form class=\"row g-3\"\r\n");
      out.write("						action=\"http://localhost:8080/Highlands/import/list.htm\"\r\n");
      out.write("						method=\"post\">\r\n");
      out.write("						<div class=\"form-group last mb-3\">\r\n");
      out.write("							<label style=\"font-size: 18px; color: black; font-weight: bold;\">Nhân\r\n");
      out.write("								Viên Nhập: </label> <label\r\n");
      out.write("								style=\"font-size: 18px; color: darkred; font-weight: bold;\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${nv}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</label>\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("						<div class=\"col-md-2\">\r\n");
      out.write("							<label for=\"manhaphang\">Mã Nhập Hàng</label> <input\r\n");
      out.write("								class=\"form-control\" type=\"text\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${manhaphang}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" disabled>\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("						<div class=\"col-md-2\">\r\n");
      out.write("							<label>Ngày Nhập</label> <input class=\"form-control\" type=\"text\"\r\n");
      out.write("								value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${thoigiannhaphang}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" disabled>\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("						<div class=\"col-md-3\">\r\n");
      out.write("							<label>Chọn Nguyên Liệu</label><br> <select id=\"mySelect\"\r\n");
      out.write("								class=\"form-control\" name=\"chonnguyenlieu\">\r\n");
      out.write("								");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("							</select>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"col-md-2\">\r\n");
      out.write("							<label for=\"soluong\">Nhập Số Lượng</label> <input type=\"number\"\r\n");
      out.write("								min=\"1\" values=\"1\" class=\"form-control\"\r\n");
      out.write("								placeholder=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.DONVI}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" name=\"soluong\">\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("						<div class=\"col-md-2\">\r\n");
      out.write("							<label for=\"dongia\">Nhập Đơn Giá</label> <input type=\"number\"\r\n");
      out.write("								min=\"0\" class=\"form-control\" values=\"0\" placeholder=\"VNĐ\"\r\n");
      out.write("								min=\"0\" step=\"100\" name=\"dongia\">\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("						<div class='parent' class=\"col-md-2\">\r\n");
      out.write("							<div class='child float-left-child' style=\"margin-left: 28em\">\r\n");
      out.write("								");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("								<p5 class=\"text-success\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${message1}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</p5>\r\n");
      out.write("								<p5 class=\"text-danger\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${message0}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</p5>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<hr\r\n");
      out.write("							style=\"box-sizing: border-box; height: 1.5px; width: 100%; border: 1px solid black;\">\r\n");
      out.write("						");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("						");
      if (_jspx_meth_c_005fif_005f2(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("						<div class=\"form-inline col-5\">\r\n");
      out.write("							<span id=\"result1\"></span>\r\n");
      out.write("						</div>\r\n");
      out.write("					</form>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"card mb-4\">\r\n");
      out.write("					<div class=\"card-header\"\r\n");
      out.write("						style=\"font-size: 20px; color: black; font-weight: bold;\">\r\n");
      out.write("						DANH SÁCH NGUYÊN LIỆU NHẬP</div>\r\n");
      out.write("					<div class=\"card-body\">\r\n");
      out.write("						<table id=\"datatablesSimple\">\r\n");
      out.write("							<thead>\r\n");
      out.write("								<tr>\r\n");
      out.write("									<th>Tên Hàng Hóa</th>\r\n");
      out.write("									<th>Đơn Vị</th>\r\n");
      out.write("									<th>Số Lượng Tồn</th>\r\n");
      out.write("									<th>Số Lượng Nhập</th>\r\n");
      out.write("									<th>Đơn Giá</th>\r\n");
      out.write("									<th>Tổng Số Lượng Tồn Mới</th>\r\n");
      out.write("								</tr>\r\n");
      out.write("							</thead>\r\n");
      out.write("							<tfoot>\r\n");
      out.write("								<tr>\r\n");
      out.write("									<th>Tên Hàng Hóa</th>\r\n");
      out.write("									<th>Đơn Vị</th>\r\n");
      out.write("									<th>Số Lượng Tồn Cũ</th>\r\n");
      out.write("									<th>Số Lượng Nhập</th>\r\n");
      out.write("									<th>Đơn Giá</th>\r\n");
      out.write("									<th>Tổng Số Lượng Tồn Mới</th>\r\n");
      out.write("								</tr>\r\n");
      out.write("							</tfoot>\r\n");
      out.write("							<tbody>\r\n");
      out.write("								");
      if (_jspx_meth_c_005fforEach_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("							</tbody>\r\n");
      out.write("						</table>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</main>\r\n");
      out.write("		<footer class=\"py-4 bg-light mt-auto\">\r\n");
      out.write("			<div class=\"container-fluid px-4\">\r\n");
      out.write("				<div class=\"d-flex align-items-center justify-content-between small\">\r\n");
      out.write("					<div class=\"text-muted\">Copyright &copy; Your Website 2022</div>\r\n");
      out.write("					<div>\r\n");
      out.write("						<a href=\"#\">Privacy Policy</a> &middot; <a href=\"#\">Terms\r\n");
      out.write("							&amp; Conditions</a>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</footer>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("	<script>\r\n");
      out.write("		$(document).ready(function() {\r\n");
      out.write("			// Initialize the DataTable\r\n");
      out.write("			var dataTable = $('datatablesSimple').DataTable();\r\n");
      out.write("\r\n");
      out.write("			// Catch the change event of the select element\r\n");
      out.write("			$('mySelect').on('change', function() {\r\n");
      out.write("				var selectedValue = $(this).val(); // Get the selected value\r\n");
      out.write("\r\n");
      out.write("				// Set the search input value and trigger the search\r\n");
      out.write("				dataTable.search(selectedValue).draw();\r\n");
      out.write("			});\r\n");
      out.write("		});\r\n");
      out.write("	</script>\r\n");
      out.write("	<script\r\n");
      out.write("		src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js\"\r\n");
      out.write("		crossorigin=\"anonymous\"></script>\r\n");
      out.write("	<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${root}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/quanly/js/scripts.js\"></script>\r\n");
      out.write("	<script src=\"https://cdn.jsdelivr.net/npm/simple-datatables@latest\"\r\n");
      out.write("		crossorigin=\"anonymous\"></script>\r\n");
      out.write("	<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${root}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/quanly/js/datatables-simple-demo.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f0_reused = false;
    try {
      _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f0.setParent(null);
      // /WEB-INF/views/quanly/nhaphang.jsp(6,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setVar("root");
      // /WEB-INF/views/quanly/nhaphang.jsp(6,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/quanly/nhaphang.jsp(6,0) '${pageContext.servletContext.contextPath}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${pageContext.servletContext.contextPath}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
      if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      _jspx_th_c_005fset_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /WEB-INF/views/quanly/nhaphang.jsp(79,8) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/quanly/nhaphang.jsp(79,8) '${dsnl}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${dsnl}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /WEB-INF/views/quanly/nhaphang.jsp(79,8) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("item");
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("									<option value=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.MANL}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write('"');
            out.write('>');
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.TEN}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</option>\r\n");
            out.write("								");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /WEB-INF/views/quanly/nhaphang.jsp(98,8) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${btnStatus=='1'}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("									<button name=\"btnAdd\" class=\"btn btn-success\">Nhập mặt\r\n");
          out.write("										hàng</button>\r\n");
          out.write("									<button\r\n");
          out.write("										onclick=\"location.href='http://localhost:8080/Highlands/import/reload.htm'\"\r\n");
          out.write("										class=\"btn btn-outline-dark\" type=\"button\">Xóa phiếu\r\n");
          out.write("										nhập</button>\r\n");
          out.write("								");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f1_reused = false;
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent(null);
      // /WEB-INF/views/quanly/nhaphang.jsp(112,6) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${btnStatus=='1'}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("							<div>\r\n");
          out.write("								<label for=\"btnSave\" style=\"font-size: 17px; color: black;\">Lưu\r\n");
          out.write("									thông tin phiếu nhập: </label>\r\n");
          out.write("								<button class=\"btn btn-danger\" name=\"btnSave\">\r\n");
          out.write("									<i class=\"glyphicon glyphicon-ok-sign\"></i> LƯU\r\n");
          out.write("								</button>\r\n");
          out.write("								<br> <br> <label for=\"btnHuy\"\r\n");
          out.write("									style=\"font-size: 17px; color: black;\">Hủy thông tin\r\n");
          out.write("									phiếu nhập: </label>\r\n");
          out.write("								<button\r\n");
          out.write("									onclick=\"location.href='http://localhost:8080/Highlands/import/defineId.htm'\"\r\n");
          out.write("									class=\"btn btn-warning\" name=\"btnHuy\" type=\"button\">HỦY</button>\r\n");
          out.write("							</div>\r\n");
          out.write("						");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      _jspx_th_c_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f2 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f2_reused = false;
    try {
      _jspx_th_c_005fif_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f2.setParent(null);
      // /WEB-INF/views/quanly/nhaphang.jsp(127,6) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f2.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${btnStatus=='0'}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f2 = _jspx_th_c_005fif_005f2.doStartTag();
      if (_jspx_eval_c_005fif_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("							<div>\r\n");
          out.write("								<button\r\n");
          out.write("									onclick=\"location.href='http://localhost:8080/Highlands/import/defineId.htm'\"\r\n");
          out.write("									class=\"btn btn-success\" type=\"button\">Trở về trang\r\n");
          out.write("									danh sách phiếu nhập</button>\r\n");
          out.write("							</div>\r\n");
          out.write("						");
          int evalDoAfterBody = _jspx_th_c_005fif_005f2.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f2);
      _jspx_th_c_005fif_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f1 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f1_reused = false;
    try {
      _jspx_th_c_005fforEach_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f1.setParent(null);
      // /WEB-INF/views/quanly/nhaphang.jsp(167,8) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/quanly/nhaphang.jsp(167,8) '${nguyenlieu}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${nguyenlieu}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /WEB-INF/views/quanly/nhaphang.jsp(167,8) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setVar("item");
      // /WEB-INF/views/quanly/nhaphang.jsp(167,8) name = varStatus type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setVarStatus("loop");
      int[] _jspx_push_body_count_c_005fforEach_005f1 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f1 = _jspx_th_c_005fforEach_005f1.doStartTag();
        if (_jspx_eval_c_005fforEach_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("									<tr>\r\n");
            out.write("										<td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.TEN}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("										<td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.DONVI}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("										<td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.SLTON}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("										<td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.SOLUONG}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("										<td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.DONGIA}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("										<td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.SLTON + item.SOLUONG}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("									</tr>\r\n");
            out.write("								");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f1.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f1[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f1.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f1.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f1);
      _jspx_th_c_005fforEach_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f1_reused);
    }
    return false;
  }
}
